"""initial schema

Revision ID: 5731680400b7
Revises: 
Create Date: 2026-09-29 20:18:56.159678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5731680400b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'state', 'name')
    )
    op.create_table('feed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('h3_cell', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_feed_events_h3_cell'), 'feed_events', ['h3_cell'], unique=False)
    op.create_index(op.f('ix_feed_events_kind'), 'feed_events', ['kind'], unique=False)
    op.create_index(op.f('ix_feed_events_observed_at'), 'feed_events', ['observed_at'], unique=False)
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('license_note', sa.String(length=300), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotspots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('fatalities', sa.Integer(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('trained_through', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('area_name', sa.String(length=200), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('h3_cells',
    sa.Column('cell', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('dist_state_border_km', sa.Float(), nullable=True),
    sa.Column('dist_lga_border_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['admin_areas.id'], ),
    sa.PrimaryKeyConstraint('cell')
    )
    op.create_index(op.f('ix_h3_cells_state'), 'h3_cells', ['state'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_last4', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('community', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lga_id'], ['admin_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_hash')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('fmt', sa.String(length=10), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_valid', sa.Integer(), nullable=False),
    sa.Column('rows_committed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('committed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_alert_id'), 'alert_deliveries', ['alert_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('h3_cell', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('cause', sa.String(length=40), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=False),
    sa.Column('injured', sa.Integer(), nullable=False),
    sa.Column('displaced', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=80), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lga_id'], ['admin_areas.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_ref', name='uq_incident_source_ref')
    )
    op.create_index(op.f('ix_incidents_h3_cell'), 'incidents', ['h3_cell'], unique=False)
    op.create_index(op.f('ix_incidents_occurred_at'), 'incidents', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_incidents_source'), 'incidents', ['source'], unique=False)
    op.create_index(op.f('ix_incidents_state'), 'incidents', ['state'], unique=False)
    op.create_index('ix_incidents_state_time', 'incidents', ['state', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_synthetic'), 'incidents', ['synthetic'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell', sa.String(length=16), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell'], ['h3_cells.cell'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell', 'week_start', 'model_version')
    )
    op.create_index(op.f('ix_risk_scores_cell'), 'risk_scores', ['cell'], unique=False)
    op.create_index(op.f('ix_risk_scores_week_start'), 'risk_scores', ['week_start'], unique=False)
    op.create_table('inbound_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_sms_phone_hash'), 'inbound_sms', ['phone_hash'], unique=False)
    op.create_table('incident_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('by_user', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['by_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_status_events_incident_id'), 'incident_status_events', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_status_events_incident_id'), table_name='incident_status_events')
    op.drop_table('incident_status_events')
    op.drop_index(op.f('ix_inbound_sms_phone_hash'), table_name='inbound_sms')
    op.drop_table('inbound_sms')
    op.drop_index(op.f('ix_risk_scores_week_start'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_cell'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_incidents_synthetic'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index('ix_incidents_state_time', table_name='incidents')
    op.drop_index(op.f('ix_incidents_state'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_occurred_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_h3_cell'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_alert_deliveries_alert_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_table('uploads')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_h3_cells_state'), table_name='h3_cells')
    op.drop_table('h3_cells')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('model_runs')
    op.drop_table('hotspots')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_feed_events_observed_at'), table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_kind'), table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_h3_cell'), table_name='feed_events')
    op.drop_table('feed_events')
    op.drop_table('admin_areas')
    # ### end Alembic commands ###
